---
- name: this is a test k8 playbook for ansibleautomation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get a list of all pods from any namespace
      community.kubernetes.k8s_info:
        kind: Pod
        # label_selectors:
        #   - sean
        validate_certs: false
      register: pod_list

    - name: debug everything to terminal window
      debug:
        msg: "{{ pod_list }}"
      when: pod_list.resources | length  < 2

    - name: generate report and show in terminal window
      debug:
        msg: "{{ lookup('template', 'templates/report.j2') }}"
